# Generated by Django 5.1.6 on 2025-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
